services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spheredb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
     context: ./backend
     dockerfile: Sphere.Api/Dockerfile
    depends_on:
      - postgres
      - search-engine
      - background-remover
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=spheredb;Username=postgres;Password=password
      - FILE_STORAGE_PATH=/app/uploads
    ports:
      - "5000:5000"
    volumes:
      - uploads_data:/app/uploads
    restart: unless-stopped
  
  search-engine:
    build:
      context: ./backend/services/SearchEngine
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - search_data:/app/search-data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped

  background-remover:
    build:
      context: ./backend/services/background-remover
      dockerfile: Dockerfile
    command: "api --host 0.0.0.0 --port 5002"
    ports:
      - "5002:5002"
    volumes:
      - remover_data:/app/remover-data
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:5000/api

volumes:
  postgres_data:
  uploads_data:
  search_data:
  remover_data: