// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sphere.Infrastructure.Persistance;

#nullable disable

namespace Sphere.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260401141939_AddedNewProps")]
    partial class AddedNewProps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sphere.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9827f22f-a79a-da9a-d435-2223e419a145"),
                            CreatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2217),
                            Name = "T-Shirt",
                            UpdatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2219)
                        },
                        new
                        {
                            Id = new Guid("177d825b-36e8-d9ab-4b93-e03b212dbfe2"),
                            CreatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2251),
                            Name = "Long Sleeve Shirt",
                            UpdatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2251)
                        },
                        new
                        {
                            Id = new Guid("8b4b0500-a80b-30c6-1761-1b99e6bf1f3f"),
                            CreatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2264),
                            Name = "Blouse",
                            UpdatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2264)
                        },
                        new
                        {
                            Id = new Guid("464b5ae7-5b60-de3a-dcce-3e98dace883a"),
                            CreatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2268),
                            Name = "Jacket",
                            UpdatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2268)
                        },
                        new
                        {
                            Id = new Guid("d92e166e-bca2-3076-7e0a-249786f4951e"),
                            CreatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2272),
                            Name = "Coat",
                            UpdatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2272)
                        },
                        new
                        {
                            Id = new Guid("e99548c0-13c7-3264-78a3-df15426030cd"),
                            CreatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2277),
                            Name = "Blazer",
                            UpdatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2277)
                        },
                        new
                        {
                            Id = new Guid("d1f37c34-1d7a-df71-9641-ba489fc0e0a0"),
                            CreatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2281),
                            Name = "Jeans",
                            UpdatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2281)
                        },
                        new
                        {
                            Id = new Guid("b223cd6e-b69c-1818-8451-cdf0f35d4704"),
                            CreatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2285),
                            Name = "Pants",
                            UpdatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2285)
                        },
                        new
                        {
                            Id = new Guid("7595c37a-01b7-93bc-aeb9-a7a1473a57c3"),
                            CreatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2288),
                            Name = "Shorts",
                            UpdatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2288)
                        },
                        new
                        {
                            Id = new Guid("6a72b4cc-64c0-c5c7-411a-5a6f70a1dc70"),
                            CreatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2292),
                            Name = "Leggings",
                            UpdatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2292)
                        },
                        new
                        {
                            Id = new Guid("cb67e7c8-3faa-5411-6b37-2c04e36eb531"),
                            CreatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2298),
                            Name = "Joggers",
                            UpdatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2299)
                        },
                        new
                        {
                            Id = new Guid("d96fed16-c3cd-aebe-3c49-075184bb5b96"),
                            CreatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2302),
                            Name = "Sweatpants",
                            UpdatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2303)
                        },
                        new
                        {
                            Id = new Guid("3c23e841-e0bb-ee3e-90cc-371b01175388"),
                            CreatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2306),
                            Name = "Dress",
                            UpdatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2306)
                        },
                        new
                        {
                            Id = new Guid("a937c8eb-a54d-6fb0-d0be-cfb3cdaa92c0"),
                            CreatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2309),
                            Name = "Skirt",
                            UpdatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2309)
                        },
                        new
                        {
                            Id = new Guid("c9aa9c37-9419-afd5-983d-32bd0a2f0557"),
                            CreatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2312),
                            Name = "Sweater",
                            UpdatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2313)
                        },
                        new
                        {
                            Id = new Guid("841bc02f-5d0c-32ee-4551-211edad39bdf"),
                            CreatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2316),
                            Name = "Pullover",
                            UpdatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2316)
                        },
                        new
                        {
                            Id = new Guid("650a1cb3-a76d-1e45-246d-2d220f50a986"),
                            CreatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2319),
                            Name = "Cardigan",
                            UpdatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2320)
                        },
                        new
                        {
                            Id = new Guid("7953797d-9211-fb4b-a10d-3f98f1623a48"),
                            CreatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2322),
                            Name = "Hoodie",
                            UpdatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2323)
                        },
                        new
                        {
                            Id = new Guid("627a0da1-ffaa-2f59-4eec-bcf2fe7fad9b"),
                            CreatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2327),
                            Name = "Hat",
                            UpdatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2327)
                        },
                        new
                        {
                            Id = new Guid("9734d588-a9f4-5829-c67c-73a9f2f52df3"),
                            CreatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2331),
                            Name = "Cap",
                            UpdatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2331)
                        },
                        new
                        {
                            Id = new Guid("2aec747c-a90c-0c95-64f8-28fa155c3a0d"),
                            CreatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2334),
                            Name = "Scarf",
                            UpdatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2334)
                        },
                        new
                        {
                            Id = new Guid("f1da3f64-f5fe-8d4e-ef75-1f54b706cd60"),
                            CreatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2337),
                            Name = "Gloves",
                            UpdatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2337)
                        },
                        new
                        {
                            Id = new Guid("0e2624ea-76f5-8940-bd80-4dad0885468b"),
                            CreatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2340),
                            Name = "Sneakers",
                            UpdatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2341)
                        },
                        new
                        {
                            Id = new Guid("b9657e79-cdc5-a20d-5a93-2f2b0947b94b"),
                            CreatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2344),
                            Name = "Boots",
                            UpdatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2344)
                        },
                        new
                        {
                            Id = new Guid("6b0d6657-f7e4-ce7c-ccfd-861400f11e4d"),
                            CreatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2347),
                            Name = "High Heels",
                            UpdatedAt = new DateTime(2026, 4, 1, 14, 19, 38, 835, DateTimeKind.Utc).AddTicks(2347)
                        });
                });

            modelBuilder.Entity("Sphere.Domain.ClothingItems.ClothingItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BoughtAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Brand")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Material")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Store")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ClothingItems", (string)null);
                });

            modelBuilder.Entity("Sphere.Domain.MediaFiles.MediaFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("MediaFiles", (string)null);
                });

            modelBuilder.Entity("Sphere.Domain.ClothingItems.ClothingItem", b =>
                {
                    b.OwnsOne("Sphere.Domain.ClothingItems.ValueObjects.Price", "Price", b1 =>
                        {
                            b1.Property<Guid>("ClothingItemId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("PriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("PriceCurrency");

                            b1.HasKey("ClothingItemId");

                            b1.ToTable("ClothingItems");

                            b1.WithOwner()
                                .HasForeignKey("ClothingItemId");
                        });

                    b.Navigation("Price");
                });
#pragma warning restore 612, 618
        }
    }
}
